# -------------------------------------------
# Script to identify and create a prioritization list of ensemble members to use to test sensitivity of ecosystem models to weather vs. climate
# The met analyzed here generated by splicing together many data products and propogating uncertainty & variable covariance
# The Github Repository for the workflow for this can be found here: https://github.com/PalEON-Project/modeling_met_ensemble
#
# Notes: Until we get empirical met filtering working, we'll just use members whose PDSI doesn't go INSANE and is "representative" of the GCM
# -------------------------------------------

# -------------------------------------------
# 1. Identify inputs, outputs etc.
# -------------------------------------------
# The file path to where our ensembel is stored
path.dat <- "~/Desktop/Research/met_ensembles/data/met_ensembles/HARVARD/"
path.out <- "../data/"

# Read in the monthly summary data
pdsi.mo   <- read.csv(file.path(path.dat, "aggregated/month", "PDSI_AllMembers.csv"), row.names=1)
temp.mo   <- read.csv(file.path(path.dat, "aggregated/month", "Temperature_AllMembers.csv"), row.names=1)
precip.mo <- read.csv(file.path(path.dat, "aggregated/month", "Precipitation_AllMembers.csv"), row.names=1)

n.mems <- ncol(pdsi.mo) # Current ensemble member size
names(pdsi.mo)[1:10]

GCMs <- unique(unlist(lapply(stringr::str_split(names(pdsi.mo), "_"), function(x) x[1])))

# -------------------------------------------
